### PR TITLE
Remove UAL

### LINKED ISSUE #110: add proton sdk auth
https://www.npmjs.com/package/@proton/web-sdk

### PR DESCRIPTION
**Pull request by tetogomez**
### What does this PR do?

- Resolve #110 

### Steps to test

1. first step
2. next step

#### CheckList

- [] Follow proper Markdown format
- [] The content is adequate
- [] The content is available in both english and spanish
- [] I Ran a spell check

### CODE REVIEW

**Review by xavier506 — APPROVED** [review]
Cannot test on testnet (seems wallet only works for mainnet)

other than that LGTM

**Comment by adriexnet** [comment]
@tetogomez please remove ual from package dependencies

**Review by adriexnet — APPROVED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM

**Pull request merged**
